### ISSUE TITLE
The position of light sources is not computed correctly for the entirety of the displays.

### ISSUE THREAD

**Issue by vr-thi** [vr-thi/CAVE#1]
![20171113_145926](https://user-images.githubusercontent.com/29986366/33242985-72829c84-d2dd-11e7-8658-3d419d8d8841.jpg)
In more complex scenes, one sees inconsistencies in shadows between displays.

Most likely, the light sources do not get transformed.

**Comment by cornerfarmer** [comment]
Apparently Unity uses the fov value of the active camera for calculating/clipping shadows. As we set the projection matrix directly in the AsymmetricFrustum.cs skript, the fov value was not updated and thats why shadows were clipped incorrect.
Now the fov should always be set correctly after calculating the projection matrix.
